name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Install Node
        uses: actions/setup-node@master
      - name: Install dependencies
        run: npm install
      - name: Build Critical CSS
        run: npm run critical
      - name: Build Site
        run: npm run build
